on:
  issues:
    types:
      - opened
  workflow_dispatch:

concurrency: add-link

jobs:
  update_issue:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
      issues: write

    steps:
      - uses: actions/checkout@v4
      - name: Process new link request
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module -Name PowerShellForGitHub
          Set-GitHubConfiguration -DisableTelemetry
          . ./build/scripts/AkaUtils.ps1
          Set-AkaGitHubAuth
          Update-AllOpenGitHubIssues
          Write-PublicSiteData
